from pathlib import Path

MODELS_DIR = Path("./ml/training/models")

TICKERS = {
    "APPL" : "Apple Inc.",
    "MSFT" : "Microsoft Corp.",
    "GOOGL" : "Alphabet Inc.",
    "AMZN" : "Amazon.com Inc.",
    "META" : "Meta Platforms Inc.",
    "NVDA" : "NVIDIA Corp.",
    "TSLA" : "Tesla Inc.",
    "JPM"  : "JPMorgan Chase & Co.",
    "BAC"  : "Bank of America Corp.",
    "XOM"  : "Exxon Mobil Corp.",
    "KO"   : "Coca-Cola Co.",
    "PEP"  : "PepsiCo Inc.",
    "WMT"  : "Walmart Inc.",
    "HD"   : "Home Depot Inc.",
    "DIS"  : "The Walt Disney Co.",

    "RELIANCE.NS"  : "Reliance Industries Ltd.",
    "TCS.NS"       : "Tata Consultancy Services Ltd.",
    "INFY.NS" : "Infosys Ltd.",
    "HDFCBANK.NS" : "HDFC Bank Ltd.",
    "ICICIBANK.NS" : "ICICI Bank Ltd.",
    "SBIN.NS" : "State Bank of India",
    "AXISBANK.NS" : "Axis Bank Ltd.",
    "KOTAKBANK.NS" : "Kotak Mahindra Bank Ltd.",
    "INDUSINDBK.NS" : "IndusInd Bank Ltd.",

    "HINDUNILVR.NS" : "Hindustan Unilever Ltd.",
    "ITC.NS" : "ITC Ltd.",
    "NESTLEIND.NS" : "Nestle India Ltd.",
    "BRITANNIA.NS" : "Britannia Industries Ltd.",
    "LT.NS" : "Larsen & Toubro Ltd.",
    "ULTRACEMCO.NS" : "UltraTech Cement Ltd.",
    "GRASIM.NS" : "Grasim Industries Ltd.",
    "ADANIENT.NS" : "Adani Enterprises Ltd.",
    "TATAMOTORS.NS" : "Tata Motors Ltd.",
    "M&M.NS" : "Mahindra & Mahindra Ltd.",
    "MARUTI.NS" : "Maruti Suzuki India Ltd.",
    "BAJAJ-AUTO.NS" : "Bajaj Auto Ltd.",
    "EICHERMOT.NS" : "Eicher Motors Ltd.",
    "HEROMOTOCO.NS" : "Hero MotoCorp Ltd.",
    "BHARTIARTL.NS" : "Bharti Airtel Ltd.",
    "IDEA.NS" : "Vodafone Idea Ltd.",
    "ASIANPAINT.NS" : "Asian Paints Ltd.",
    "TITAN.NS" : "Titan Company Ltd.",
    "HAVELLS.NS" : "Havells India Ltd.",
    "SUNPHARMA.NS" : "Sun Pharmaceutical Industries Ltd.",
    "DRREDDY.NS" : "Dr. Reddy's Laboratories Ltd.",
    "CIPLA.NS" : "Cipla Ltd.",
    "DIVISLAB.NS" : "Divi's Laboratories Ltd.",
    "APOLLOHOSP.NS" : "Apollo Hospitals Enterprise Ltd.",
    "ALKEM.NS" : "Alkem Laboratories Ltd.",
    "POWERGRID.NS" : "Power Grid Corporation of India Ltd.",
    "NTPC.NS" : "NTPC Ltd.",
    "ONGC.NS" : "Oil & Natural Gas Corporation Ltd.",
    "BPCL.NS" : "Bharat Petroleum Corporation Ltd.",
    "IOC.NS" : "Indian Oil Corporation Ltd.",
    "COALINDIA.NS" : "Coal India Ltd.",
    "GAIL.NS" : "GAIL (India) Ltd.",
    "HCLTECH.NS" : "HCL Technologies Ltd.",
    "TECHM.NS" : "Tech Mahindra Ltd.",
    "WIPRO.NS" : "Wipro Ltd.",
    "LTIM.NS" : "L&T Infotech Ltd.",
    "DMART.NS" : "Avenue Supermarts Ltd.",
    "TRENT.NS" : "Trent Ltd.",
    "TATACONSUM.NS" : "Tata Consumer Products Ltd.",
    "PIDILITIND.NS" : "Pidilite Industries Ltd.",
    "BERGEPAINT.NS" : "Berger Paints India Ltd.",
    "BAJFINANCE.NS" : "Bajaj Finance Ltd.",
    "BAJAJFINSV.NS" : "Bajaj Finserv Ltd.",
    "HDFCLIFE.NS" : "HDFC Life Insurance Company Ltd.",
    "SBILIFE.NS" : "SBILife Insurance Company Ltd.",
    "ICICIPRULI.NS" : "ICICI Prudential Life Insurance Company Ltd.",
    "SHREECEM.NS" : "Shree Cement Ltd.",
    "AMBUJACEM.NS" : "Ambuja Cements Ltd.",
    "JSWSTEEL.NS" : "JSW Steel Ltd.",
    "TATASTEEL.NS" : "Tata Steel Ltd.",
    "HINDALCO.NS" : "Hindalco Industries Ltd.",
    "UPL.NS" : "UPL Ltd.",
    "SRF.NS" : "SRF Ltd.",
    "ABB.NS" : "ABB India Ltd.",
    "SIEMENS.NS" : "Siemens Ltd.",
    "INDIGO.NS" : "InterGlobe Aviation Ltd.",
    "IRCTC.NS" : "Indian Railway Catering & Tourism Corp. Ltd.",
    "DLF.NS" : "DLF Ltd.",
    "GODREJPROP.NS" : "Godrej Properties Ltd.",
    "ICICIGI.NS" : "ICICI Lombard General Insurance Company Ltd.",
    "MUTHOOTFIN.NS" : "Muthoot Finance Ltd.",
    "CHOLAFIN.NS" : "Cholamandalam Investment and Finance Company Ltd.",
    "PFC.NS" : "Power Finance Corporation Ltd.",
    "RECLTD.NS" : "REC Ltd.",
    "BANKBARODA.NS" : "Bank of Baroda",
    "CANBK.NS" : "Canara Bank",
}
